### ISSUE TITLE
Problem occurs when converting vmd camera files.

### ISSUE THREAD

**Issue by Yunhyuk-Jeong** [ShiinaRinne/MMD6UnityTool#1]
When a converted and generated file is inserted into the Camera object, Missing! occurs.

![image](https://github.com/ShiinaRinne/MMD6UnityTool/assets/29269126/0e004eea-a69c-4f60-b1d2-1daed3fe4766)

**Comment by ShiinaRinne** [comment]
Based on the structure of anim, you need to create two empty objects in the scene as follows, and rename the middle object to Distance.
![image](https://github.com/ShiinaRinne/MMD6UnityTool/assets/45081750/0300b13b-3862-4e93-9496-48f1aaa45b3f)

**Comment by Yunhyuk-Jeong** [comment]
Thank you for your kind reply, and I'm sorry to ask you again.

As you told me, I applied `Distance` as a child of `GameObject`, placed `Camera` as a child, and then applied Anim to `GameObject`.

Nevertheless, `GameObject : Local Position` and `GameObject : Local Rotation`, `Distance : Local Position` are still Missing.

Can I get an answer?

Thank you very much.

![image](https://github.com/ShiinaRinne/MMD6UnityTool/assets/29269126/2269a1bc-064c-4768-83b2-462e22b97f85)

**Comment by ShiinaRinne** [comment]
I've updated the code, please  use the latest version recreate the anim file using 
https://github.com/ShiinaRinne/MMD6UnityTool/releases/tag/0.0.3

And the Animator component should be added to the top-level object as follows
![image](https://github.com/ShiinaRinne/MMD6UnityTool/assets/45081750/b6039a35-d4f8-41a9-b9f2-9233affb716f)

![image](https://github.com/ShiinaRinne/MMD6UnityTool/assets/45081750/45653afc-a98f-46e1-82a9-0ec44588523a)

![image](https://github.com/ShiinaRinne/MMD6UnityTool/assets/45081750/54592271-4331-40d5-a825-d6ce722a234f)

**Comment by Yunhyuk-Jeong** [comment]
Thank you for your kind help.
I hope you have a good day!
