### ISSUE TITLE
I think the camera conversion is not working properly.

### ISSUE THREAD

**Issue by Yunhyuk-Jeong** [ShiinaRinne/MMD6UnityTool#2]
https://www.youtube.com/watch?v=Z6dviiOQAJ4

This video is the original video of the motion.

If you look at the video, the center of the camera doesn't leave the avatar.

On the other hand, the camera converted using this asset works like this.

https://github.com/ShiinaRinne/MMD6UnityTool/assets/29269126/2ea5e816-1c99-4ec1-9b27-9c0936e6b9f2

I think this is the problem because the position of the camera does not change and only rotates.

Thank you for making a good asset, and I would really appreciate it if you could check this and reflect it.

**Comment by ShiinaRinne** [comment]
Can you provide me with the original VMD file for testing? My email is [sr@yae.ac.cn](mailto:sr@yae.ac.cn)

**Comment by Yunhyuk-Jeong** [comment]
We have identified the problem! Since `GameObject` is the central axis, and `Camera` should be the format around it, it will be solved when the 98th line of `VMDCameraConverter.cs` changes to `cameraData.length * mmd4unity_unit`, or when Camera's y reaches 180!

**Comment by ShiinaRinne** [comment]
Yes, I forgot to mention this.
In the current version, it is necessary to rotate the Camera 180° to match most of the MMD Motions(which I have tested).
In only a few special cases, it is necessary to rotate the character by another 180°.

If modified according to your proposal, I think it may be necessary to rotate the character 180 in most cases, which may be more troublesome for development.
![B`URUDJ0VK01 @@GOOF5{IM](https://github.com/ShiinaRinne/MMD6UnityTool/assets/45081750/0188db08-71d5-4dbb-b32d-5124a8655f68)

I was not aware of this issue before, and it will take some time to test and decide which method is better. Do you have any ideas?

**Comment by Yunhyuk-Jeong** [comment]
I think you just need to add that to ReadMe!
