### ISSUE TITLE
Seems no matter which version of unity this prevents the Tool from functioning at all 

### ISSUE THREAD

**Issue by Pockyman1** [ShiinaRinne/MMD6UnityTool#3]
Assets\MMD6UnityTool-master\Editor\AnimationHelpers.cs(8,29): error CS0234: The type or namespace name 'Universal' does not exist in the namespace 'UnityEngine.Rendering' (are you missing an assembly reference?)

**Comment by ShiinaRinne** [comment]
My mistake, it only works in Unity URP, and you can safely remove it(it has no practical effect)

**Comment by Pockyman1** [comment]
Oh ok Thank you was looking all over the place on what was causing before making a post here considering last update was back in august or so.

**Comment by ShiinaRinne** [comment]
No problem, I hope this can help you~
As long as I haven't archived the repository, it indicates that I still have the intention to maintain it

>  last update was back in august or so.

btw, this is simply because there hasn't been any functionality worth updating.
